# Generated by Django 5.1.6 on 2025-02-15 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaApp', '0003_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='venta',
            name='correo_cliente',
            field=models.EmailField(default='cliente@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion_cliente',
            field=models.CharField(default='Dirección no especificada', max_length=200),
        ),
        migrations.AddField(
            model_name='venta',
            name='nombre_cliente',
            field=models.CharField(default='Cliente Anónimo', max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sistemaApp.venta')),
            ],
        ),
    ]
